services:
  - type: web
    name: vibegnewsbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GPTBOTS_API_KEY
        sync: false
