services:
  - type: web
    name: vibegnews_bot
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GPTBOTS_API_KEY
        sync: false
      - key: GPTBOTS_AGENT_ID
        sync: false
